### ISSUE TITLE
Pip installation doesn't work for python2

### ISSUE THREAD

**Issue by jonwedell** [bmrb-io/PyBMRB#11]
Pip installation works for on python3. In python2 it fails unless all of the dependency packages are already installed.

This appears to be because the setup.py script attempts to import the version from pybmrb, but that requires that pybmrb be able to import all of its dependencies - which aren't yet installed.

```code
wedell@manowar:~$ pip2  install pybmrb
Collecting pybmrb
  Downloading https://files.pythonhosted.org/packages/e8/46/027c63298d5e8bf58a8de85ebd837f9e16ca241029bc58d736a8bf05befc/pybmrb-1.2.5.tar.gz (39.5MB)
    100% |████████████████████████████████| 39.5MB 49kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-79zrkp/pybmrb/setup.py", line 6, in <module>
        from pybmrb.csviz import __version__
      File "pybmrb/csviz.py", line 11, in <module>
        import plotly
    ImportError: No module named plotly
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-79zrkp/pybmrb/
```

I'm not sure why this works in python3 - perhaps the installation script installs the dependencies before attempting to resolve the version.

I found some documentation on ways to address this here: https://packaging.python.org/guides/single-sourcing-package-version/

**Comment by kumar-physics** [comment]
I think the issue is importing version before installation. Thanks of the link I will test the methods and implement one. For time being I have manually entered the version in the setup file. The next version I will implement a method to get the true version from source 
https://github.com/uwbmrb/PyBMRB/pull/12/commits/4e451e2220bd5fd67624bc1a9cd2d265e615a26f
