### ISSUE TITLE
Open generated histogram in browser when not in notebook mode

### ISSUE THREAD

**Issue by jonwedell** [bmrb-io/PyBMRB#9]
When not in histogram mode, I think it would be helpful to automatically open the generated histogram in the web browser. This is straightforward to accomplish as well:

```python
import os
from webbrowser import open_new_tab
histogram_url = 'file://' + os.path.realpath(histogram_html_file)
open_new_tab(histogram_filename)```

**Comment by kumar-physics** [comment]
It does open by default, but sometimes it is  annoying so I set the variable False. It can be enabled with csviz._AUTOOPEN = True. Then it will open in web browser each time. 
Do you think is it good to set this True by default?

**Comment by jonwedell** [comment]
I would suggest setting it to True, yes. I think most users would want to see the histogram immediately after generating it, at least when they are first using the library. I think only after that would they potentially begin using it in automated scripts such that they would want to disable that feature.

I suppose it would make sense to change that variable from a private module one to a public one as well, and document it.

**Comment by jonwedell** [comment]
Another possibility is adding `open_in_browser` (or something like that) as an optional argument to the various histogram commands, set to True by default (or set to the value of _AUTOOPEN).

**Comment by kumar-physics** [comment]
I have updated the code set the _AUTOOPEN True , which is available in a minor update soon

**Comment by kumar-physics** [comment]
Done 
https://github.com/uwbmrb/PyBMRB/pull/10/commits/09ad10eb370f7c9fb11b694c0d4cd1f04ed81ae5
